### ISSUE TITLE
Sorry，we don't know what is Archit.

### ISSUE THREAD

**Issue by mrhyh** [intelygenz/Archit-iOS#1]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with what info we expect. You can delete those lines once you've filled in the info.
>
> Please remove this line and everything above it before submitting.

## What did you do?

ℹ Please replace this with what you did.

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.

## What happened instead?

ℹ Please replace this with of what happened instead.

## Archit Environment

**Xcode version:**
**Swift version:**
**Platform(s) running Archit:**
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by alexruperez** [comment]
@mrhyh Archit is an iOS Architecture documentation with a sample app. Thanks! 😺

**Comment by Gargo** [comment]
@alexruperez need much more details. For example it is unclear why did you use `AppProtocol`, `AppDelegateProtocol` and `AppManagerProtocol`.
Additionally why do you use so many extensions? You even write `AppManagerProtocol` protocol and extension one after another.

**Comment by alexruperez** [comment]
@Gargo everything is designed to make the AppManager assumes all the responsibilities of the AppDelegate, including all those extensions, in this way we can abstract from the system AppDelegate, we can test application behaviour with a mocked AppManager through AppManagerProtocol, test the AppManager implementation independently...

**Comment by Gargo** [comment]
@alexruperez ok, you delegate responsibility from one object/class/protocol to another one. And your scheme describes it.
But the question is why do you delegate responsibility to multiple entities while it seems enough to deal with one entity only? I really want to understand this architecture but it is too hard without detailed info
